### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by ayotec2015** [cloudposse/terraform-aws-key-pair#28]
HI, 

I tried to use the module this way but the problem is the resource will fail because the module hasn't generated the key yet. Do you have an inbuilt way to create the resource below through the module so I can refer to it in AWS launch configuration via terraform

module "ssh_key_pair" {
  source                = "git::https://github.com/cloudposse/terraform-aws-key-pair.git?ref=master"
  namespace             = "default"
  stage                 = "${var.name}"
  name                  = "${var.name}"
  ssh_public_key_path   = "${path.root}"
  generate_ssh_key      = "true"
  private_key_extension = "_private_key.pem"
  public_key_extension  = "_public_key.pub"
  chmod_command         = "chmod 600 %v"
}

 resource "aws_key_pair" "keys" {
   key_name   = "default-${var.name}-${var.name}_public_key.pub"
    key_name   = "${module.ssh_key_pair.id}"
   public_key = "${file("${path.root}/default-${var.name}-${var.name}_public_key.pub")}"

 depends_on = [
     "local_file.default-eks_nodes_martini-eks_nodes_martini_public_key.pub",
   ]
 }

**Comment by jamengual** [comment]
this has been addressed in version 0.11.0 @ayotec2015 closing
