### ISSUE TITLE
Downloaded key should have ".pem" extension

### ISSUE THREAD

**Issue by wcmjunior** [cloudposse/terraform-aws-key-pair#4]
The downloaded key file should have the ".pem" extension.

**Comment by osterman** [comment]
Can you provide some more context? We're following the `openssh` convention which does *not* typically use extensions for the private key, while uses the `.pub` extension for the public key.

**Comment by wcmjunior** [comment]
@osterman, the default extension when you create the key using aws console is ".pem", that's the reason of my sugestion. :)

**Comment by osterman** [comment]
Fixed in https://github.com/cloudposse/terraform-aws-key-pair/pull/7
